globalThis.SHOW_TERRAIN_REBUILD_DEBUG = false;

const clamp = (value, min, max) => Math.max(min, Math.min(max, value));

const controls = [
  { key: 'seed', label: 'Terrain Seed', type: 'number', min: 1, max: 999999999, step: 1, section: 'Planet' },
  { key: 'width', label: 'Width', type: 'range', min: 1800, max: 7200, step: 100, section: 'Planet' },
  { key: 'height', label: 'Height', type: 'range', min: 1800, max: 7200, step: 100, section: 'Planet' },
  { key: 'biome', label: 'Biome', type: 'select', options: ['scrap', 'forest', 'crystal', 'ember'], section: 'Planet' },
  { key: 'type', label: 'Type', type: 'select', options: ['crashPlanet', 'denseAtmospherePlanet', 'largeMineral', 'crystalCluster', 'cave'], section: 'Planet' },
  { key: 'landingXRatio', label: 'Landing X', type: 'range', min: 0.08, max: 0.92, step: 0.01, section: 'Planet' },
  { key: 'caveDensity', label: 'Cave Density', type: 'range', min: 0, max: 2, step: 0.05, section: 'Terrain' },
  { key: 'oreDensity', label: 'Ore Density', type: 'range', min: 0, max: 2, step: 0.05, section: 'Terrain' },
  { key: 'starterBase', label: 'Starter Base', type: 'checkbox', section: 'Structures' },
  { key: 'engineTower', label: 'Engine Tower', type: 'checkbox', section: 'Structures' },
  { key: 'innerAtmosphere', label: 'Inner Ring', type: 'range', min: 800, max: 8000, step: 100, section: 'Rings' },
  { key: 'outerAtmosphere', label: 'Outer Ring', type: 'range', min: 1200, max: 12000, step: 100, section: 'Rings' },
  { key: 'ringIndex', label: 'Circle Index', type: 'range', min: 0, max: 4, step: 1, section: 'World' },
  { key: 'ringSize', label: 'Circle Size', type: 'range', min: 12000, max: 60000, step: 1000, section: 'World' },
  { key: 'worldDistance', label: 'P01 Distance', type: 'range', min: 0, max: 36000, step: 250, section: 'World' },
  { key: 'surfaceGapMin', label: 'Surface Gap Min', type: 'range', min: 1000, max: 18000, step: 250, section: 'Spacing' },
  { key: 'surfaceGapMax', label: 'Surface Gap Max', type: 'range', min: 1000, max: 22000, step: 250, section: 'Spacing' },
];

const state = {
  seed: 1010101,
  width: 3400,
  height: 3400,
  biome: 'scrap',
  type: 'crashPlanet',
  landingXRatio: 0.22,
  caveDensity: 1,
  oreDensity: 1,
  starterBase: true,
  engineTower: true,
  innerAtmosphere: 2500,
  outerAtmosphere: 5000,
  ringIndex: 0,
  ringSize: 36000,
  worldDistance: 9000,
  surfaceGapMin: 5000,
  surfaceGapMax: 7000,
};

let TerrainGrid = null;
let BuildingSystem = null;
let gameBalance = null;
let current = null;
let renderQueued = false;

function getRoot() {
  return document.querySelector('[data-plt-gen]');
}

function format(value) {
  if (typeof value === 'boolean') return value ? 'on' : 'off';
  if (typeof value === 'number') return Math.round(value * 100) / 100;
  return value;
}

function makeIslandConfig() {
  const size = { width: Math.round(state.width), height: Math.round(state.height) };
  const distance = Math.max(0, Number(state.worldDistance) || 0);
  const angle = -0.42;
  return {
    id: 'crashPlanet',
    planetTag: 'P01',
    tag: 'P01',
    name: 'Menderfall',
    type: state.type,
    biome: state.biome,
    kind: 'story',
    ringIndex: Math.round(state.ringIndex),
    circleName: ['Inner Circle', 'Inner Mid Circle', 'Mid Circle', 'Outer Mid Circle', 'Outer Circle'][Math.round(state.ringIndex)] || 'Inner Circle',
    atmosphereClass: state.type === 'denseAtmospherePlanet' ? 'dense' : 'stable',
    gravityStabilizerRequirement: state.type === 'denseAtmospherePlanet' ? 2 : 1,
    worldPosition: {
      x: Math.round(Math.cos(angle) * distance),
      y: Math.round(Math.sin(angle) * distance),
    },
    size,
    discovered: true,
    dangerLevel: 1,
    landingZoneRadius: Math.round(state.innerAtmosphere),
    atmosphereDepth: Math.round(state.outerAtmosphere),
    terrainSeed: Math.round(state.seed),
    baseCamp: Boolean(state.starterBase),
    resources: ['stoneOre', 'ironDust', 'copperShards', 'moonCrystal', 'crystallizedStone', 'redCrystal'],
    animals: [],
    layoutId: 'crashPlanet',
    requiredScannerLevel: 1,
    description: 'P01 tutorial planet preset generated by PLT Gen.',
  };
}

function withGeneratorBalance(callback) {
  const terrain = gameBalance.terrain || {};
  const mining = gameBalance.mining || {};
  const previous = {
    caveDensity: terrain.caveDensity,
    oreDensity: terrain.oreDensity,
    inner: mining.planetInnerAtmosphereDepth,
    outer: mining.planetAtmosphereDepth,
  };
  terrain.caveDensity = Number(state.caveDensity);
  terrain.oreDensity = Number(state.oreDensity);
  mining.planetInnerAtmosphereDepth = Number(state.innerAtmosphere);
  mining.planetAtmosphereDepth = Number(state.outerAtmosphere);
  try {
    return callback();
  } finally {
    terrain.caveDensity = previous.caveDensity;
    terrain.oreDensity = previous.oreDensity;
    mining.planetInnerAtmosphereDepth = previous.inner;
    mining.planetAtmosphereDepth = previous.outer;
  }
}

function generatePlanet() {
  const island = makeIslandConfig();
  const world = {
    width: island.size.width,
    height: island.size.height,
    landingX: Math.round(island.size.width * state.landingXRatio),
    landingY: Math.round(island.size.height * 0.32),
  };
  const terrain = withGeneratorBalance(() => TerrainGrid.createForIsland(island, world));
  island.terrain = terrain;
  island.getSurfaceLocalAtAngle = (angle, offset = 0) => terrain.getSurfacePointAtAngle(angle, offset);

  const structures = {};
  if (state.starterBase) {
    const building = new BuildingSystem({});
    structures.base = building.stampStarterBaseOnIsland(island, {
      surfaceX: terrain.landingX,
      surfaceY: terrain.landingY,
    })?.lab || null;
  }
  if (state.engineTower) {
    const building = new BuildingSystem({});
    structures.engineTower = building.stampStarterEngineTowerOnIsland(island) || null;
  }
  current = { island, world, terrain, structures };
  return current;
}

function drawPreview() {
  const canvas = document.querySelector('[data-preview]');
  if (!canvas || !current) return;
  const ctx = canvas.getContext('2d');
  const { island, terrain } = current;
  const width = canvas.width;
  const height = canvas.height;
  const centerX = width * 0.5;
  const centerY = height * 0.5;
  const surfaceRadius = terrain.planetRadius;
  const outerRadius = surfaceRadius + Number(state.outerAtmosphere);
  const scale = Math.min(width, height) * 0.44 / Math.max(1, outerRadius);

  ctx.clearRect(0, 0, width, height);
  const bg = ctx.createRadialGradient(centerX, centerY, 20, centerX, centerY, width * 0.68);
  bg.addColorStop(0, '#182638');
  bg.addColorStop(0.58, '#07111f');
  bg.addColorStop(1, '#020611');
  ctx.fillStyle = bg;
  ctx.fillRect(0, 0, width, height);

  ctx.save();
  ctx.translate(centerX, centerY);
  ctx.scale(scale, scale);
  drawRing(ctx, surfaceRadius + Number(state.outerAtmosphere), '#4d82c9', [90, 70], 10 / scale);
  drawRing(ctx, surfaceRadius + Number(state.innerAtmosphere), '#ffd36b', [38, 34], 7 / scale);
  ctx.drawImage(terrain.renderCanvas || buildTerrainImage(terrain), -terrain.width * 0.5, -terrain.height * 0.5);
  ctx.restore();

  ctx.fillStyle = '#dff9ff';
  ctx.font = '800 13px system-ui, sans-serif';
  ctx.fillText('Outer', 18, 28);
  ctx.fillStyle = '#ffd36b';
  ctx.fillText('Inner', 18, 48);
  ctx.fillStyle = 'rgba(236, 231, 216, 0.76)';
  ctx.fillText(`${island.planetTag} ${island.name}`, 18, height - 24);
}

function buildTerrainImage(terrain) {
  const canvas = document.createElement('canvas');
  canvas.width = terrain.width;
  canvas.height = terrain.height;
  const ctx = canvas.getContext('2d');
  terrain.draw(ctx, { x: 0, y: 0 }, terrain.width, terrain.height, { lighting: false });
  return terrain.renderCanvas || canvas;
}

function drawRing(ctx, radius, color, dash, lineWidth) {
  ctx.save();
  ctx.strokeStyle = color;
  ctx.globalAlpha = 0.74;
  ctx.lineWidth = lineWidth;
  ctx.setLineDash(dash);
  ctx.beginPath();
  ctx.arc(0, 0, radius, 0, Math.PI * 2);
  ctx.stroke();
  ctx.restore();
}

function updateStats() {
  const stats = document.querySelector('[data-stats]');
  if (!stats || !current) return;
  const radius = Math.round(current.terrain.planetRadius);
  const innerCenterRadius = Math.round(radius + Number(state.innerAtmosphere));
  const outerCenterRadius = Math.round(radius + Number(state.outerAtmosphere));
  const outerOverlapAtMin = Math.max(0, Number(state.outerAtmosphere) * 2 - Number(state.surfaceGapMin));
  stats.innerHTML = `
    <div><strong>${radius}</strong><span>surface radius</span></div>
    <div><strong>${innerCenterRadius}</strong><span>inner ring from center</span></div>
    <div><strong>${outerCenterRadius}</strong><span>outer ring from center</span></div>
    <div><strong>${state.surfaceGapMin}-${state.surfaceGapMax}</strong><span>target surface gap</span></div>
    <div><strong>${outerOverlapAtMin}</strong><span>outer overlap at min gap</span></div>
  `;
}

function render() {
  renderQueued = false;
  generatePlanet();
  drawPreview();
  updateStats();
}

function scheduleRender() {
  if (renderQueued) return;
  renderQueued = true;
  window.requestAnimationFrame(render);
}

function buildControls() {
  const container = document.querySelector('[data-controls]');
  if (!container) return;
  const sections = new Map();
  controls.forEach((control) => {
    if (!sections.has(control.section)) {
      const section = document.createElement('section');
      section.className = 'plt-control-section';
      section.innerHTML = `<h2>${control.section}</h2>`;
      sections.set(control.section, section);
      container.append(section);
    }
    sections.get(control.section).append(createControl(control));
  });
}

function createControl(control) {
  const row = document.createElement('label');
  row.className = `plt-control is-${control.type}`;
  const value = document.createElement('output');
  value.textContent = format(state[control.key]);
  let input = null;
  if (control.type === 'select') {
    input = document.createElement('select');
    control.options.forEach((option) => {
      const el = document.createElement('option');
      el.value = option;
      el.textContent = option;
      input.append(el);
    });
    input.value = state[control.key];
  } else {
    input = document.createElement('input');
    input.type = control.type;
    if (control.type !== 'checkbox') {
      input.min = control.min;
      input.max = control.max;
      input.step = control.step;
      input.value = state[control.key];
    } else {
      input.checked = Boolean(state[control.key]);
    }
  }
  input.addEventListener('input', () => {
    if (control.type === 'checkbox') state[control.key] = input.checked;
    else if (control.type === 'select') state[control.key] = input.value;
    else state[control.key] = Number(input.value);
    if (control.key === 'outerAtmosphere') state.outerAtmosphere = Math.max(state.outerAtmosphere, state.innerAtmosphere + 100);
    if (control.key === 'surfaceGapMin') state.surfaceGapMax = Math.max(state.surfaceGapMax, state.surfaceGapMin);
    value.textContent = format(state[control.key]);
    syncControlOutputs();
    scheduleRender();
  });
  row.append(document.createElement('span'), input, value);
  row.querySelector('span').textContent = control.label;
  return row;
}

function syncControlOutputs() {
  document.querySelectorAll('.plt-control').forEach((row) => {
    const label = row.querySelector('span')?.textContent;
    const control = controls.find((entry) => entry.label === label);
    const input = row.querySelector('input, select');
    const output = row.querySelector('output');
    if (!control || !input || !output) return;
    if (input.type === 'checkbox') input.checked = Boolean(state[control.key]);
    else input.value = state[control.key];
    output.textContent = format(state[control.key]);
  });
}

function createExportJson() {
  if (!current) generatePlanet();
  const { terrain, getSurfaceLocalAtAngle, ...island } = current.island;
  return {
    schemaVersion: 1,
    tool: 'Moonrock PLT Gen',
    savedAt: new Date().toISOString(),
    role: 'tutorial-po1',
    planetTag: 'P01',
    generator: { ...state },
    island,
    structures: current.structures,
    terrain: terrain.serialize(),
  };
}

function savePo1Json() {
  const payload = createExportJson();
  const text = JSON.stringify(payload, null, 2);
  localStorage.setItem('moonrock:dev:po1PlanetPreset', text);
  const blob = new Blob([text], { type: 'application/json' });
  const link = document.createElement('a');
  link.href = URL.createObjectURL(blob);
  link.download = `P01-planet-${payload.generator.seed}.json`;
  document.body.append(link);
  link.click();
  link.remove();
  window.setTimeout(() => URL.revokeObjectURL(link.href), 1000);
}

async function boot() {
  [{ TerrainGrid }, { BuildingSystem }, { gameBalance }] = await Promise.all([
    import('../systems/TerrainGrid.js?v=158'),
    import('../systems/BuildingSystem.js?v=158'),
    import('../data/gameBalance.js?v=158'),
  ]);
  state.innerAtmosphere = gameBalance.mining?.planetInnerAtmosphereDepth || state.innerAtmosphere;
  state.outerAtmosphere = gameBalance.mining?.planetAtmosphereDepth || state.outerAtmosphere;
  state.ringSize = gameBalance.mining?.ringSize || state.ringSize;
  state.surfaceGapMin = gameBalance.mining?.planetSurfaceSpacingMin || state.surfaceGapMin;
  state.surfaceGapMax = gameBalance.mining?.planetSurfaceSpacingMax || state.surfaceGapMax;
  buildControls();
  document.querySelector('[data-randomize]')?.addEventListener('click', () => {
    state.seed = Math.floor(1 + Math.random() * 999999999);
    syncControlOutputs();
    scheduleRender();
  });
  document.querySelector('[data-save-po1]')?.addEventListener('click', savePo1Json);
  scheduleRender();
  getRoot()?.classList.add('is-ready');
}

boot().catch((error) => {
  const root = getRoot();
  if (root) root.innerHTML = `<pre class="plt-error">${error?.stack || error}</pre>`;
});
